// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.model.Data;

#nullable disable

namespace backend.model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315212014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("backend.model.Models.Accounts", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountSID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("AccountID");

                    b.HasIndex(new[] { "AccountID" }, "IX_Accounts_AccountID")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountSID" }, "IX_Accounts_AccountSID")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("backend.model.Models.Descriptions", b =>
                {
                    b.Property<int>("DescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionSID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("DescriptionID");

                    b.HasIndex(new[] { "DescriptionID" }, "IX_Descriptions_DescriptionID")
                        .IsUnique();

                    b.HasIndex(new[] { "DescriptionSID" }, "IX_Descriptions_DescriptionSID")
                        .IsUnique();

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("backend.model.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double?>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("DescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("TransactionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionSID")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DescriptionID");

                    b.HasIndex(new[] { "TransactionID" }, "IX_Transactions_TransactionID")
                        .IsUnique();

                    b.HasIndex(new[] { "TransactionSID" }, "IX_Transactions_TransactionSID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("backend.model.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSID")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex(new[] { "UserID" }, "IX_Users_UserID")
                        .IsUnique();

                    b.HasIndex(new[] { "UserSID" }, "IX_Users_UserSID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.model.Models.Transactions", b =>
                {
                    b.HasOne("backend.model.Models.Accounts", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID");

                    b.HasOne("backend.model.Models.Descriptions", "Description")
                        .WithMany("Transactions")
                        .HasForeignKey("DescriptionID");

                    b.Navigation("Account");

                    b.Navigation("Description");
                });

            modelBuilder.Entity("backend.model.Models.Accounts", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("backend.model.Models.Descriptions", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
