// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.model.DbModels;

#nullable disable

namespace backend.model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821151500_AddUniqueIndexToDescriptionName")]
    partial class AddUniqueIndexToDescriptionName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("backend.model.DbModels.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("AccountID");

                    b.HasIndex(new[] { "AccountID" }, "IX_Accounts_AccountID")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountSID" }, "IX_Accounts_AccountSID")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Description", b =>
                {
                    b.Property<int>("DescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("DescriptionID");

                    b.HasIndex(new[] { "DescriptionID" }, "IX_Descriptions_DescriptionID")
                        .IsUnique();

                    b.HasIndex(new[] { "DescriptionName" }, "IX_Descriptions_DescriptionName")
                        .IsUnique();

                    b.HasIndex(new[] { "DescriptionSID" }, "IX_Descriptions_DescriptionSID")
                        .IsUnique();

                    b.ToTable("Descriptions", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double?>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("DescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("TransactionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DescriptionID");

                    b.HasIndex(new[] { "TransactionID" }, "IX_Transactions_TransactionID")
                        .IsUnique();

                    b.HasIndex(new[] { "TransactionSID" }, "IX_Transactions_TransactionSID")
                        .IsUnique();

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex(new[] { "UserID" }, "IX_Users_UserID")
                        .IsUnique();

                    b.HasIndex(new[] { "UserSID" }, "IX_Users_UserSID")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Views.VwAccountsList", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("account_name");

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("account_number");

                    b.Property<string>("AccountSID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("account_sid");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("bank_name");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("status");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("transaction_count");

                    b.ToTable((string)null);

                    b.ToView("vw_accounts_list", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Views.VwDescriptionsList", b =>
                {
                    b.Property<string>("DescriptionName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description_name");

                    b.Property<string>("DescriptionSID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description_sid");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("status");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("usage_count");

                    b.ToTable((string)null);

                    b.ToView("vw_descriptions_list", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Views.VwTransactionsList", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("account_name");

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("account_number");

                    b.Property<string>("AccountSID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("account_sid");

                    b.Property<double?>("Balance")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("balance");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("bank_name");

                    b.Property<double?>("Credit")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("credit");

                    b.Property<double?>("Debit")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("debit");

                    b.Property<string>("DescriptionName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description_name");

                    b.Property<string>("DescriptionSID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description_sid");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("status");

                    b.Property<string>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("transaction_date");

                    b.Property<string>("TransactionSID")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("transaction_sid");

                    b.ToTable((string)null);

                    b.ToView("vw_transactions_list", (string)null);
                });

            modelBuilder.Entity("backend.model.DbModels.Transaction", b =>
                {
                    b.HasOne("backend.model.DbModels.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID");

                    b.HasOne("backend.model.DbModels.Description", "Description")
                        .WithMany("Transactions")
                        .HasForeignKey("DescriptionID");

                    b.Navigation("Account");

                    b.Navigation("Description");
                });

            modelBuilder.Entity("backend.model.DbModels.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("backend.model.DbModels.Description", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
